const NigerianStates = [
  {
    title: "Abia",
    lgas: [
      { title: "Aba North" },
      { title: "Aba South" },
      { title: "Arochukwu" },
      { title: "Bende" },
      { title: "Ikwuano" },
      { title: "Isiala Ngwa North" },
      { title: "Isiala Ngwa South" },
      { title: "Isuikwuato" },
      { title: "Obi Ngwa" },
      { title: "Ohafia" },
      { title: "Osisioma" },
      { title: "Ugwunagbo" },
      { title: "Ukwa East" },
      { title: "Ukwa West" },
      { title: "Umuahia North" },
      { title: "Umuahia South" },
      { title: "Umu Nneochi" },
    ],
  },
  {
    title: "Adamawa",
    lgas: [
      { title: "Demsa" },
      { title: "Fufore" },
      { title: "Ganye" },
      { title: "Girei" },
      { title: "Guyuk" },
      { title: "Hong" },
      { title: "Jada" },
      { title: "Lamurde" },
      { title: "Madagali" },
      { title: "Maiha" },
      { title: "Mayo-Belwa" },
      { title: "Michika" },
      { title: "Mubi North" },
      { title: "Mubi South" },
      { title: "Numan" },
      { title: "Shelleng" },
      { title: "Song" },
      { title: "Toungo" },
      { title: "Yola North" },
      { title: "Yola South" },
    ],
  },
  {
    title: "Akwa Ibom",
    lgas: [
      { title: "Abak" },
      { title: "Eastern Obolo" },
      { title: "Eket" },
      { title: "Esit Eket" },
      { title: "Essien Udim" },
      { title: "Etim Ekpo" },
      { title: "Etinan" },
      { title: "Ibeno" },
      { title: "Ibesikpo Asutan" },
      { title: "Ibiono Ibom" },
      { title: "Ika" },
      { title: "Ikono" },
      { title: "Ikot Abasi" },
      { title: "Ikot Ekpene" },
      { title: "Ini" },
      { title: "Itu" },
      { title: "Mbo" },
      { title: "Mkpat Enin" },
      { title: "Nsit Atai" },
      { title: "Nsit Ibom" },
      { title: "Nsit Ubium" },
      { title: "Obot Akara" },
      { title: "Okobo" },
      { title: "Onna" },
      { title: "Oron" },
      { title: "Oruk Anam" },
      { title: "Udung Uko" },
      { title: "Ukanafun" },
      { title: "Uruan" },
      { title: "Urue-Offong/Oruko" },
      { title: "Uyo" },
    ],
  },
  {
    title: "Anambra",
    lgas: [
      { title: "Aguata" },
      { title: "Anambra East" },
      { title: "Anambra West" },
      { title: "Anaocha" },
      { title: "Awka North" },
      { title: "Awka South" },
      { title: "Ayamelum" },
      { title: "Dunukofia" },
      { title: "Ekwusigo" },
      { title: "Idemili North" },
      { title: "Idemili South" },
      { title: "Ihiala" },
      { title: "Njikoka" },
      { title: "Nnewi North" },
      { title: "Nnewi South" },
      { title: "Ogbaru" },
      { title: "Onitsha North" },
      { title: "Onitsha South" },
      { title: "Orumba North" },
      { title: "Orumba South" },
      { title: "Oyi" },
    ],
  },
  {
    title: "Bauchi",
    lgas: [
      { title: "Alkaleri" },
      { title: "Bauchi" },
      { title: "Bogoro" },
      { title: "Damban" },
      { title: "Darazo" },
      { title: "Dass" },
      { title: "Gamawa" },
      { title: "Ganjuwa" },
      { title: "Giade" },
      { title: "Itas/Gadau" },
      { title: "Jama'are" },
      { title: "Katagum" },
      { title: "Kirfi" },
      { title: "Misau" },
      { title: "Ningi" },
      { title: "Shira" },
      { title: "Tafawa Balewa" },
      { title: "Toro" },
      { title: "Warji" },
      { title: "Zaki" },
    ],
  },
  {
    title: "Bayelsa",
    lgas: [
      { title: "Brass" },
      { title: "Ekeremor" },
      { title: "Kolokuma/Opokuma" },
      { title: "Nembe" },
      { title: "Ogbia" },
      { title: "Sagbama" },
      { title: "Southern Ijaw" },
      { title: "Yenagoa" },
    ],
  },
  {
    title: "Benue",
    lgas: [
      { title: "Ado" },
      { title: "Agatu" },
      { title: "Apa" },
      { title: "Buruku" },
      { title: "Gboko" },
      { title: "Guma" },
      { title: "Gwer East" },
      { title: "Gwer West" },
      { title: "Katsina-Ala" },
      { title: "Konshisha" },
      { title: "Kwande" },
      { title: "Logo" },
      { title: "Makurdi" },
      { title: "Obi" },
      { title: "Ogbadibo" },
      { title: "Ohimini" },
      { title: "Oju" },
      { title: "Okpokwu" },
      { title: "Oturkpo" },
      { title: "Tarka" },
      { title: "Ukum" },
      { title: "Ushongo" },
      { title: "Vandeikya" },
    ],
  },
  {
    title: "Borno",
    lgas: [
      { title: "Abadam" },
      { title: "Askira/Uba" },
      { title: "Bama" },
      { title: "Bayo" },
      { title: "Biu" },
      { title: "Chibok" },
      { title: "Damboa" },
      { title: "Dikwa" },
      { title: "Gubio" },
      { title: "Guzamala" },
      { title: "Gwoza" },
      { title: "Hawul" },
      { title: "Jere" },
      { title: "Kaga" },
      { title: "Kala/Balge" },
      { title: "Konduga" },
      { title: "Kukawa" },
      { title: "Kwaya Kusar" },
      { title: "Mafa" },
      { title: "Magumeri" },
      { title: "Maiduguri" },
      { title: "Marte" },
      { title: "Mobbar" },
      { title: "Monguno" },
      { title: "Ngala" },
      { title: "Nganzai" },
      { title: "Shani" },
    ],
  },
  {
    title: "Cross River",
    lgas: [
      { title: "Abi" },
      { title: "Akamkpa" },
      { title: "Akpabuyo" },
      { title: "Bakassi" },
      { title: "Bekwarra" },
      { title: "Biase" },
      { title: "Boki" },
      { title: "Calabar Municipal" },
      { title: "Calabar South" },
      { title: "Etung" },
      { title: "Ikom" },
      { title: "Obanliku" },
      { title: "Obubra" },
      { title: "Obudu" },
      { title: "Odukpani" },
      { title: "Ogoja" },
      { title: "Yakuur" },
      { title: "Yala" },
    ],
  },
  {
    title: "Delta",
    lgas: [
      { title: "Aniocha North" },
      { title: "Aniocha South" },
      { title: "Bomadi" },
      { title: "Burutu" },
      { title: "Ethiope East" },
      { title: "Ethiope West" },
      { title: "Ika North East" },
      { title: "Ika South" },
      { title: "Isoko North" },
      { title: "Isoko South" },
      { title: "Ndokwa East" },
      { title: "Ndokwa West" },
      { title: "Okpe" },
      { title: "Oshimili North" },
      { title: "Oshimili South" },
      { title: "Patani" },
      { title: "Sapele" },
      { title: "Udu" },
      { title: "Ughelli North" },
      { title: "Ughelli South" },
      { title: "Ukwuani" },
      { title: "Uvwie" },
      { title: "Warri North" },
      { title: "Warri South" },
      { title: "Warri South West" },
    ],
  },
  {
    title: "Ebonyi",
    lgas: [
      { title: "Abakaliki" },
      { title: "Afikpo North" },
      { title: "Afikpo South" },
      { title: "Ebonyi" },
      { title: "Ezza North" },
      { title: "Ezza South" },
      { title: "Ikwo" },
      { title: "Ishielu" },
      { title: "Ivo" },
      { title: "Izzi" },
      { title: "Ohaozara" },
      { title: "Ohaukwu" },
      { title: "Onicha" },
    ],
  },
  {
    title: "Edo",
    lgas: [
      { title: "Akoko-Edo" },
      { title: "Egor" },
      { title: "Esan Central" },
      { title: "Esan North-East" },
      { title: "Esan South-East" },
      { title: "Esan West" },
      { title: "Etsako Central" },
      { title: "Etsako East" },
      { title: "Etsako West" },
      { title: "Igueben" },
      { title: "Ikpoba Okha" },
      { title: "Orhionmwon" },
      { title: "Oredo" },
      { title: "Ovia North-East" },
      { title: "Ovia South-West" },
      { title: "Owan East" },
      { title: "Owan West" },
      { title: "Uhunmwonde" },
    ],
  },
  {
    title: "Ekiti",
    lgas: [
      { title: "Ado Ekiti" },
      { title: "Efon" },
      { title: "Ekiti East" },
      { title: "Ekiti South-West" },
      { title: "Ekiti West" },
      { title: "Emure" },
      { title: "Gbonyin" },
      { title: "Ido Osi" },
      { title: "Ijero" },
      { title: "Ikere" },
      { title: "Ikole" },
      { title: "Ilejemeje" },
      { title: "Irepodun/Ifelodun" },
      { title: "Ise/Orun" },
      { title: "Moba" },
      { title: "Oye" },
    ],
  },
  {
    title: "Enugu",
    lgas: [
      { title: "Aninri" },
      { title: "Awgu" },
      { title: "Enugu East" },
      { title: "Enugu North" },
      { title: "Enugu South" },
      { title: "Ezeagu" },
      { title: "Igbo Etiti" },
      { title: "Igbos Eze North" },
      { title: "Igbo Eze South" },
      { title: "Isi Uzo" },
      { title: "Nkanu East" },
      { title: "Nkanu West" },
      { title: "Nsukka" },
      { title: "Oji River" },
      { title: "Udenu" },
      { title: "Udi" },
      { title: "Uzo Uwani" },
    ],
  },
  {
    title: "Gombe",
    lgas: [
      { title: "Akko" },
      { title: "Balanga" },
      { title: "Billiri" },
      { title: "Dukku" },
      { title: "Funakaye" },
      { title: "Gombe" },
      { title: "Kaltungo" },
      { title: "Kwami" },
      { title: "Nafada" },
      { title: "Shongom" },
      { title: "Yamaltu/Deba" },
    ],
  },
  {
    title: "Imo",
    lgas: [
      { title: "Aboh Mbaise" },
      { title: "Ahiazu Mbaise" },
      { title: "Ehime Mbano" },
      { title: "Ezinihitte" },
      { title: "Ideato North" },
      { title: "Ideato South" },
      { title: "Ihitte/Uboma" },
      { title: "Ikeduru" },
      { title: "Isiala Mbano" },
      { title: "Isu" },
      { title: "Mbaitoli" },
      { title: "Ngor Okpala" },
      { title: "Njaba" },
      { title: "Nkwerre" },
      { title: "Nwangele" },
      { title: "Obowo" },
      { title: "Oguta" },
      { title: "Ohaji/Egbema" },
      { title: "Okigwe" },
      { title: "Orlu" },
      { title: "Orsu" },
      { title: "Oru East" },
      { title: "Oru West" },
      { title: "Owerri Municipal" },
      { title: "Owerri North" },
      { title: "Owerri West" },
      { title: "Unuimo" },
    ],
  },
  {
    title: "Jigawa",
    lgas: [
      { title: "Auyo" },
      { title: "Babura" },
      { title: "Biriniwa" },
      { title: "Birnin Kudu" },
      { title: "Buji" },
      { title: "Dutse" },
      { title: "Gagarawa" },
      { title: "Garki" },
      { title: "Gumel" },
      { title: "Guri" },
      { title: "Gwaram" },
      { title: "Hadejia" },
      { title: "Jahun" },
      { title: "Kafin Hausa" },
      { title: "Kazaure" },
      { title: "Kiri Kasama" },
      { title: "Kiyawa" },
      { title: "Maigatari" },
      { title: "Malam Madori" },
      { title: "Miga" },
      { title: "Ringim" },
      { title: "Roni" },
      { title: "Sule Tankarkar" },
      { title: "Taura" },
      { title: "Yankwashi" },
    ],
  },
  {
    title: "Kaduna",
    lgas: [
      { title: "Birnin Gwari" },
      { title: "Chikun" },
      { title: "Giwa" },
      { title: "Igabi" },
      { title: "Ikara" },
      { title: "Jaba" },
      { title: "Jema'a" },
      { title: "Kachia" },
      { title: "Kaduna North" },
      { title: "Kaduna South" },
      { title: "Kagarko" },
      { title: "Kajuru" },
      { title: "Kaura" },
      { title: "Kauru" },
      { title: "Kubau" },
      { title: "Kudan" },
      { title: "Lere" },
      { title: "Makarfi" },
      { title: "Sabon Gari" },
      { title: "Sanga" },
      { title: "Soba" },
      { title: "Zangon Kataf" },
      { title: "Zaria" },
    ],
  },
  {
    title: "Kano",
    lgas: [
      { title: "Ajingi" },
      { title: "Albasu" },
      { title: "Bagwai" },
      { title: "Bebeji" },
      { title: "Bichi" },
      { title: "Bunkure" },
      { title: "Dala" },
      { title: "Dambatta" },
      { title: "Dawakin Kudu" },
      { title: "Dawakin Tofa" },
      { title: "Doguwa" },
      { title: "Fagge" },
      { title: "Gabasawa" },
      { title: "Garko" },
      { title: "Garun Mallam" },
      { title: "Gaya" },
      { title: "Gezawa" },
      { title: "Gwale" },
      { title: "Gwarzo" },
      { title: "Kabo" },
      { title: "Kano Municipal" },
      { title: "Karaye" },
      { title: "Kibiya" },
      { title: "Kiru" },
      { title: "Kumbotso" },
      { title: "Kunchi" },
      { title: "Kura" },
      { title: "Madobi" },
      { title: "Makoda" },
      { title: "Minjibir" },
      { title: "Nasarawa" },
      { title: "Rano" },
      { title: "Rimin Gado" },
      { title: "Rogo" },
      { title: "Shanono" },
      { title: "Sumaila" },
      { title: "Takai" },
      { title: "Tarauni" },
      { title: "Tofa" },
      { title: "Tsanyawa" },
      { title: "Tudun Wada" },
      { title: "Ungogo" },
      { title: "Warawa" },
      { title: "Wudil" },
    ],
  },
  {
    title: "Katsina",
    lgas: [
      { title: "Bakori" },
      { title: "Batagarawa" },
      { title: "Batsari" },
      { title: "Baure" },
      { title: "Bindawa" },
      { title: "Charanchi" },
      { title: "Dan Musa" },
      { title: "Dandume" },
      { title: "Danja" },
      { title: "Daura" },
      { title: "Dutsi" },
      { title: "Dutsin Ma" },
      { title: "Faskari" },
      { title: "Funtua" },
      { title: "Ingawa" },
      { title: "Jibia" },
      { title: "Kafur" },
      { title: "Kaita" },
      { title: "Kankara" },
      { title: "Kankia" },
      { title: "Katsina" },
      { title: "Kurfi" },
      { title: "Kusada" },
      { title: "Mai'Adua" },
      { title: "Malumfashi" },
      { title: "Mani" },
      { title: "Mashi" },
      { title: "Matazu" },
      { title: "Musawa" },
      { title: "Rimi" },
      { title: "Sabuwa" },
      { title: "Safana" },
      { title: "Sandamu" },
      { title: "Zango" },
    ],
  },
  {
    title: "Kebbi",
    lgas: [
      { title: "Aleiro" },
      { title: "Arewa Dandi" },
      { title: "Argungu" },
      { title: "Augie" },
      { title: "Bagudo" },
      { title: "Birnin Kebbi" },
      { title: "Bunza" },
      { title: "Dandi" },
      { title: "Fakai" },
      { title: "Gwandu" },
      { title: "Jega" },
      { title: "Kalgo" },
      { title: "Koko/Besse" },
      { title: "Maiyama" },
      { title: "Ngaski" },
      { title: "Sakaba" },
      { title: "Shanga" },
      { title: "Suru" },
      { title: "Wasagu/Danko" },
      { title: "Yauri" },
      { title: "Zuru" },
    ],
  },
  {
    title: "Kogi",
    lgas: [
      { title: "Adavi" },
      { title: "Ajaokuta" },
      { title: "Ankpa" },
      { title: "Bassa" },
      { title: "Dekina" },
      { title: "Ibaji" },
      { title: "Idah" },
      { title: "Igalamela Odolu" },
      { title: "Ijumu" },
      { title: "Kabba/Bunu" },
      { title: "Kogi" },
      { title: "Lokoja" },
      { title: "Mopa Muro" },
      { title: "Ofu" },
      { title: "Ogori/Magongo" },
      { title: "Okehi" },
      { title: "Okene" },
      { title: "Olamaboro" },
      { title: "Omala" },
      { title: "Yagba East" },
      { title: "Yagba West" },
    ],
  },
  {
    title: "Kwara",
    lgas: [
      { title: "Asa" },
      { title: "Baruten" },
      { title: "Edu" },
      { title: "Ekiti" },
      { title: "Ifelodun" },
      { title: "Ilorin East" },
      { title: "Ilorin South" },
      { title: "Ilorin West" },
      { title: "Irepodun" },
      { title: "Isin" },
      { title: "Kaiama" },
      { title: "Moro" },
      { title: "Offa" },
      { title: "Oke Ero" },
      { title: "Oyun" },
      { title: "Pategi" },
    ],
  },
  {
    title: "Lagos",
    lgas: [
      { title: "Agege" },
      { title: "Ajeromi-Ifelodun" },
      { title: "Alimosho" },
      { title: "Amuwo-Odofin" },
      { title: "Apapa" },
      { title: "Badagry" },
      { title: "Epe" },
      { title: "Eti Osa" },
      { title: "Ibeju-Lekki" },
      { title: "Ifako-Ijaiye" },
      { title: "Ikeja" },
      { title: "Ikorodu" },
      { title: "Kosofe" },
      { title: "Lagos Island" },
      { title: "Lagos Mainland" },
      { title: "Mushin" },
      { title: "Ojo" },
      { title: "Oshodi-Isolo" },
      { title: "Shomolu" },
      { title: "Surulere" },
    ],
  },
  {
    title: "Nasarawa",
    lgas: [
      { title: "Akwanga" },
      { title: "Awe" },
      { title: "Doma" },
      { title: "Karu" },
      { title: "Keana" },
      { title: "Keffi" },
      { title: "Kokona" },
      { title: "Lafia" },
      { title: "Nasarawa" },
      { title: "Nasarawa Egon" },
      { title: "Obi" },
      { title: "Toto" },
      { title: "Wamba" },
    ],
  },
  {
    title: "Niger",
    lgas: [
      { title: "Agaie" },
      { title: "Agwara" },
      { title: "Bida" },
      { title: "Borgu" },
      { title: "Bosso" },
      { title: "Chanchaga" },
      { title: "Edati" },
      { title: "Gbako" },
      { title: "Gurara" },
      { title: "Katcha" },
      { title: "Kontagora" },
      { title: "Lapai" },
      { title: "Lavun" },
      { title: "Magama" },
      { title: "Mariga" },
      { title: "Mashegu" },
      { title: "Mokwa" },
      { title: "Munya" },
      { title: "Paikoro" },
      { title: "Rafi" },
      { title: "Rijau" },
      { title: "Shiroro" },
      { title: "Suleja" },
      { title: "Tafa" },
      { title: "Wushishi" },
    ],
  },
  {
    title: "Ogun",
    lgas: [
      { title: "Abeokuta North" },
      { title: "Abeokuta South" },
      { title: "Ado-Odo/Ota" },
      { title: "Egbado North" },
      { title: "Egbado South" },
      { title: "Ewekoro" },
      { title: "Ifo" },
      { title: "Ijebu East" },
      { title: "Ijebu North" },
      { title: "Ijebu North East" },
      { title: "Ijebu Ode" },
      { title: "Ikenne" },
      { title: "Imeko Afon" },
      { title: "Ipokia" },
      { title: "Obafemi Owode" },
      { title: "Odeda" },
      { title: "Odogbolu" },
      { title: "Ogun Waterside" },
      { title: "Remo North" },
      { title: "Shagamu" },
    ],
  },
  {
    title: "Ondo",
    lgas: [
      { title: "Akoko North-East" },
      { title: "Akoko North-West" },
      { title: "Akoko South-West" },
      { title: "Akoko South-East" },
      { title: "Akure North" },
      { title: "Akure South" },
      { title: "Ese Odo" },
      { title: "Idanre" },
      { title: "Ifedore" },
      { title: "Ilaje" },
      { title: "Ile Oluji/Okeigbo" },
      { title: "Irele" },
      { title: "Odigbo" },
      { title: "Okitipupa" },
      { title: "Ondo East" },
      { title: "Ondo West" },
      { title: "Ose" },
      { title: "Owo" },
    ],
  },
  {
    title: "Osun",
    lgas: [
      { title: "Aiyedade" },
      { title: "Aiyedire" },
      { title: "Atakunmosa East" },
      { title: "Atakunmosa West" },
      { title: "Boluwaduro" },
      { title: "Boripe" },
      { title: "Ede North" },
      { title: "Ede South" },
      { title: "Egbedore" },
      { title: "Ejigbo" },
      { title: "Ife Central" },
      { title: "Ife East" },
      { title: "Ife North" },
      { title: "Ife South" },
      { title: "Ifedayo" },
      { title: "Ifelodun" },
      { title: "Ila" },
      { title: "Ilesa East" },
      { title: "Ilesa West" },
      { title: "Irepodun" },
      { title: "Irewole" },
      { title: "Isokan" },
      { title: "Iwo" },
      { title: "Obokun" },
      { title: "Odo Otin" },
      { title: "Ola Oluwa" },
      { title: "Olorunda" },
      { title: "Oriade" },
      { title: "Orolu" },
      { title: "Osogbo" },
    ],
  },
  {
    title: "Oyo",
    lgas: [
      { title: "Afijio" },
      { title: "Akinyele" },
      { title: "Atiba" },
      { title: "Atisbo" },
      { title: "Egbeda" },
      { title: "Ibadan North" },
      { title: "Ibadan North-East" },
      { title: "Ibadan North-West" },
      { title: "Ibadan South-East" },
      { title: "Ibadan South-West" },
      { title: "Ibarapa Central" },
      { title: "Ibarapa East" },
      { title: "Ibarapa North" },
      { title: "Ido" },
      { title: "Irepo" },
      { title: "Iseyin" },
      { title: "Itesiwaju" },
      { title: "Iwajowa" },
      { title: "Kajola" },
      { title: "Lagelu" },
      { title: "Ogbomosho North" },
      { title: "Ogbomosho South" },
      { title: "Ogo Oluwa" },
      { title: "Olorunsogo" },
      { title: "Oluyole" },
      { title: "Ona Ara" },
      { title: "Orelope" },
      { title: "Ori Ire" },
      { title: "Oyo" },
      { title: "Oyo East" },
      { title: "Saki East" },
      { title: "Saki West" },
      { title: "Surulere" },
    ],
  },
  {
    title: "Plateau",
    lgas: [
      { title: "Barkin Ladi" },
      { title: "Bassa" },
      { title: "Bokkos" },
      { title: "Jos East" },
      { title: "Jos North" },
      { title: "Jos South" },
      { title: "Kanam" },
      { title: "Kanke" },
      { title: "Langtang North" },
      { title: "Langtang South" },
      { title: "Mangu" },
      { title: "Mikang" },
      { title: "Pankshin" },
      { title: "Qua'an Pan" },
      { title: "Riyom" },
      { title: "Shendam" },
      { title: "Wase" },
    ],
  },
  {
    title: "Rivers",
    lgas: [
      { title: "Abua/Odual" },
      { title: "Ahoada East" },
      { title: "Ahoada West" },
      { title: "Akuku Toru" },
      { title: "Andoni" },
      { title: "Asari-Toru" },
      { title: "Bonny" },
      { title: "Degema" },
      { title: "Eleme" },
      { title: "Emuoha" },
      { title: "Etche" },
      { title: "Gokana" },
      { title: "Ikwerre" },
      { title: "Khana" },
      { title: "Obio/Akpor" },
      { title: "Ogba/Egbema/Ndoni" },
      { title: "Ogu/Bolo" },
      { title: "Okrika" },
      { title: "Omuma" },
      { title: "Opobo/Nkoro" },
      { title: "Oyigbo" },
      { title: "Port Harcourt" },
      { title: "Tai" },
    ],
  },
  {
    title: "Sokoto",
    lgas: [
      { title: "Binji" },
      { title: "Bodinga" },
      { title: "Dange Shuni" },
      { title: "Gada" },
      { title: "Goronyo" },
      { title: "Gudu" },
      { title: "Gwadabawa" },
      { title: "Illela" },
      { title: "Isa" },
      { title: "Kebbe" },
      { title: "Kware" },
      { title: "Rabah" },
      { title: "Sabon Birni" },
      { title: "Shagari" },
      { title: "Silame" },
      { title: "Sokoto North" },
      { title: "Sokoto South" },
      { title: "Tambuwal" },
      { title: "Tangaza" },
      { title: "Tureta" },
      { title: "Wamako" },
      { title: "Wurno" },
      { title: "Yabo" },
    ],
  },
  {
    title: "Taraba",
    lgas: [
      { title: "Ardo Kola" },
      { title: "Bali" },
      { title: "Donga" },
      { title: "Gashaka" },
      { title: "Gassol" },
      { title: "Ibi" },
      { title: "Jalingo" },
      { title: "Karim Lamido" },
      { title: "Kumi" },
      { title: "Lau" },
      { title: "Sardauna" },
      { title: "Takum" },
      { title: "Ussa" },
      { title: "Wukari" },
      { title: "Yorro" },
      { title: "Zing" },
    ],
  },
  {
    title: "Yobe",
    lgas: [
      { title: "Bade" },
      { title: "Bursari" },
      { title: "Damaturu" },
      { title: "Fika" },
      { title: "Fune" },
      { title: "Geidam" },
      { title: "Gujba" },
      { title: "Gulani" },
      { title: "Jakusko" },
      { title: "Karasuwa" },
      { title: "Machina" },
      { title: "Nangere" },
      { title: "Nguru" },
      { title: "Potiskum" },
      { title: "Tarmuwa" },
      { title: "Yunusari" },
      { title: "Yusufari" },
    ],
  },
  {
    title: "Zamfara",
    lgas: [
      { title: "Anka" },
      { title: "Bakura" },
      { title: "Birnin Magaji/Kiyaw" },
      { title: "Bukkuyum" },
      { title: "Bungudu" },
      { title: "Gummi" },
      { title: "Gusau" },
      { title: "Kaura Namoda" },
      { title: "Maradun" },
      { title: "Maru" },
      { title: "Shinkafi" },
      { title: "Talata Mafara" },
      { title: "Zurmi" },
    ],
  },
];
